### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hqvv**
Correct typo

### CODE REVIEW

**Comment by hqvv** [comment]
Correct a typo error

**Comment by PatriciaLee3** [comment]
Thank you for your PR! I will correct this typo. 
Regarding other parts of this PR, personally, I believe it is safer to let people decide how to use the access (e.g., fix the SSH service) on their own. Therefore, I will keep this PR open for those who may need it. 😉

**Comment by hqvv** [comment]
sorry,the second part about fixing ssh could be submitted by mistake.
It just a note for myself.

Thank you for your great works and generous sharing!

**Comment by hqvv** [comment]
Close as the issue was fixed

**Pull request closed without merging**
